=== JoseNavio/HibernateFBI/src/main/resources/sospechosos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="DatosFederales">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Sospechoso"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Sospechoso">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Nombre"/>
        <xs:element ref="Sexo"/>
        <xs:element ref="Altura"/>
        <xs:element ref="Peso"/>
        <xs:element ref="FechaNacimiento"/>
        <xs:element minOccurs="0" ref="Foto"/>
        <xs:element ref="Delito"/>
      </xs:sequence>
      <xs:attribute name="estado" use="required" type="xs:NCName"/>
      <xs:attribute name="ficha" use="required" type="Ficha"/>
      <xs:attribute name="nombreEstado" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Nombre" type="xs:string"/>
  <xs:element name="Sexo" type="xs:NCName"/>
  <xs:element name="Altura" type="xs:integer"/>
  <xs:element name="Peso" type="xs:integer"/>
  <xs:element name="FechaNacimiento" type="xs:string"/>
  <xs:element name="Delito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Fecha"/>
        <xs:element ref="Tipo"/>
        <xs:element ref="Observaciones"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="Ficha">
    <xs:restriction base="xs:NCName">
      <xs:pattern value="[A-Z]{3}\d{3}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="Fecha" type="xs:dateTime"/>
  <xs:element name="Tipo" type="xs:NCName"/>
  <xs:element name="Observaciones" type="xs:string"/>
  <xs:element name="Foto" type="xs:NCName"/>
</xs:schema>

=== JoseNavio/HibernateFBI/src/main/resources/sospechosos01.xml
<?xml version="1.0" encoding="UTF-8"?>
<DatosFederales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="sospechosos.xsd">
	<Sospechoso ficha="AKK901" estado="NV" nombreEstado="NEVADA">
		<Nombre>Eric Flanagan</Nombre>
		<Sexo>Varón</Sexo>
		<Altura>180</Altura>
		<Peso>85</Peso>
		<FechaNacimiento>1952/03/18</FechaNacimiento>
		<Foto>eric-flanagan</Foto>
		<Delito>
			<Fecha>2019-05-12T13:45:00</Fecha>
			<Tipo>Asesinato</Tipo>
			<Observaciones><![CDATA[Buscado por las autoridades por asesinato en atraco en banco]]></Observaciones>
		</Delito>
	</Sospechoso>
	<Sospechoso ficha="LLF455" estado="TX" nombreEstado="TEXAS">
		<Nombre>Jhon Carpenter</Nombre>
		<Sexo>Varón</Sexo>
		<Altura>172</Altura>
		<Peso>78</Peso>
		<FechaNacimiento>1968/10/03</FechaNacimiento>
		<Foto>jhon-carpenter</Foto>
		<Delito>
			<Fecha>2005-03-11T00:45:00</Fecha>
			<Tipo>Asesinato</Tipo>
			<Observaciones><![CDATA[Sospechoso del asesinato de varias prostitutas en el área de El Paso en el bienio 2005-2006]]></Observaciones>
		</Delito>
	</Sospechoso>
</DatosFederales>

=== JoseNavio/HibernateFBI/src/main/resources/sospechosos02.xml
<?xml version="1.0" encoding="UTF-8"?>
<DatosFederales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="sospechosos.xsd">
	<Sospechoso ficha="LLF455" estado="TX" nombreEstado="TEXAS">
		<Nombre>Jhon Carpenter</Nombre>
		<Sexo>Varón</Sexo>
		<Altura>172</Altura>
		<Peso>78</Peso>
		<FechaNacimiento>1968/10/03</FechaNacimiento>
		<Foto>jhon-carpenter</Foto>
		<Delito>
			<Fecha>2006-03-11T01:12:00</Fecha>
			<Tipo>Asesinato</Tipo>
			<Observaciones><![CDATA[Sospechoso del asesinato de varias prostitutas en el área de Jalisco en el bienio 2005-2006]]></Observaciones>
		</Delito>
	</Sospechoso>
	<Sospechoso ficha="LLJ466" estado="LA" nombreEstado="LOS ANGELES">
		<Nombre>Malcon Mann</Nombre>
		<Sexo>Varón</Sexo>
		<Altura>178</Altura>
		<Peso>85</Peso>
		<FechaNacimiento>1972/02/15</FechaNacimiento>
		<Foto>malcon-mann</Foto>
		<Delito>
			<Fecha>2012-10-05T17:15:00</Fecha>
			<Tipo>Pedarastia</Tipo>
			<Observaciones><![CDATA[Acusado de la distribución de pornografía infantil]]></Observaciones>
		</Delito>
	</Sospechoso>
	<Sospechoso ficha="LLC223" estado="NM" nombreEstado="MINNESOTA">
		<Nombre>Panchi Martínez Arévalo</Nombre>
		<Sexo>Varón</Sexo>
		<Altura>168</Altura>
		<Peso>78</Peso>
		<FechaNacimiento>1978/11/06</FechaNacimiento>
		<Foto>panchi-martinez</Foto>		
		<Delito>
			<Fecha>2018-08-15T17:15:00</Fecha>
			<Tipo>Inmigración</Tipo>
			<Observaciones><![CDATA[Líder de una red de inmigración ilegal]]></Observaciones>
		</Delito>
	</Sospechoso>
	<Sospechoso ficha="LLJ466" estado="LA" nombreEstado="LOS ANGELES">
		<Nombre>Malcon Mann</Nombre>
		<Sexo>Varón</Sexo>
		<Altura>178</Altura>
		<Peso>85</Peso>
		<FechaNacimiento>1972/02/15</FechaNacimiento>
		<Foto>malcon-mann</Foto>
		<Delito>
			<Fecha>2018-01-05T13:15:00</Fecha>
			<Tipo>Pedarastia</Tipo>
			<Observaciones><![CDATA[Tenencia de material fotográfico]]></Observaciones>
		</Delito>
	</Sospechoso>
</DatosFederales>
